services:
  redis:
    image: "redis:alpine"
    container_name: niko-clip-redis
    networks:
      - niko-clip-network

  backend:
    build: .
    container_name: niko-clip-backend
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - niko-clip-network
    ports:
      - "8000:8000"

networks:
  niko-clip-network:
    driver: bridge